using System;

namespace TCSHoldEmPoker.Network.Define {
    public enum NetworkActivityID {
        SAMPLE                                          = 0xFFFF,

        NULL_PREFIX                                     = 0x0000,
        POKER_GAME_EVENT_PREFIX                         = 0x0100,
        POKER_GAME_INPUT_PREFIX                         = 0x0200,
        POKER_GAME_STATE_UPDATE                         = 0x0300,

        // POKER GAME EVENTS
        // Connectivity
        POKER_GAME_EVENT_PLAYER_JOIN                    = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_JOIN,
        POKER_GAME_EVENT_PLAYER_LEAVE                   = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_LEAVE,
        // Ante Progression
        POKER_GAME_EVENT_ANTE_START                     = POKER_GAME_EVENT_PREFIX | PokerGameEventType.ANTE_START,
        POKER_GAME_EVENT_ANTE_PHASE_CHANGE              = POKER_GAME_EVENT_PREFIX | PokerGameEventType.ANTE_PHASE_CHANGE,
        POKER_GAME_EVENT_ANTE_TURN_CHANGE               = POKER_GAME_EVENT_PREFIX | PokerGameEventType.ANTE_TURN_CHANGE,
        POKER_GAME_EVENT_ANTE_END                       = POKER_GAME_EVENT_PREFIX | PokerGameEventType.ANTE_END,
        // Card Dealing
        POKER_GAME_EVENT_PLAYER_CARD_DEAL               = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_CARD_DEAL,
        POKER_GAME_EVENT_COMMUNITY_CARD_DEAL            = POKER_GAME_EVENT_PREFIX | PokerGameEventType.COMMUNITY_CARD_DEAL,
        // Player Action
        POKER_GAME_EVENT_PLAYER_BET_BLIND               = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_BET_BLIND,
        POKER_GAME_EVENT_PLAYER_BET_CHECK               = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_BET_CHECK,
        POKER_GAME_EVENT_PLAYER_BET_CALL_BASIC          = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_BET_CALL_BASIC,
        POKER_GAME_EVENT_PLAYER_BET_CALL_ALL_IN         = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_BET_CALL_ALL_IN,
        POKER_GAME_EVENT_PLAYER_BET_RAISE_BASIC         = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_BET_RAISE_BASIC,
        POKER_GAME_EVENT_PLAYER_BET_RAISE_ALL_IN        = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_BET_RAISE_ALL_IN,
        POKER_GAME_EVENT_PLAYER_BET_FOLD                = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_BET_FOLD,
        // Win Condition
        POKER_GAME_EVENT_TABLE_UPDATE_MAIN_PRIZE        = POKER_GAME_EVENT_PREFIX | PokerGameEventType.UPDATE_MAIN_PRIZE_POT,
        POKER_GAME_EVENT_TABLE_CREATE_SIDE_PRIZE        = POKER_GAME_EVENT_PREFIX | PokerGameEventType.CREATE_SIDE_PRIZE_POT,
        POKER_GAME_EVENT_ALL_PLAYER_CARDS_REVEAL        = POKER_GAME_EVENT_PREFIX | PokerGameEventType.ALL_PLAYER_CARDS_REVEAL,
        POKER_GAME_EVENT_PLAYER_WIN                     = POKER_GAME_EVENT_PREFIX | PokerGameEventType.PLAYER_WIN,

        // POKER GAME INPUTS
        // Connectivity
        POKER_GAME_INPUT_PLAYER_REQUEST_JOIN            = POKER_GAME_INPUT_PREFIX | PokerGameInputType.PLAYER_REQUEST_JOIN,
        POKER_GAME_INPUT_PLAYER_REQUEST_LEAVE           = POKER_GAME_INPUT_PREFIX | PokerGameInputType.PLAYER_REQUEST_LEAVE,
        // Player Action
        POKER_GAME_INPUT_PLAYER_ACTION_BET_CHECK        = POKER_GAME_INPUT_PREFIX | PokerGameInputType.PLAYER_ACTION_BET_CHECK,
        POKER_GAME_INPUT_PLAYER_ACTION_BET_CALL         = POKER_GAME_INPUT_PREFIX | PokerGameInputType.PLAYER_ACTION_BET_CALL,
        POKER_GAME_INPUT_PLAYER_ACTION_BET_RAISE        = POKER_GAME_INPUT_PREFIX | PokerGameInputType.PLAYER_ACTION_BET_RAISE,
        POKER_GAME_INPUT_PLAYER_ACTION_BET_FOLD         = POKER_GAME_INPUT_PREFIX | PokerGameInputType.PLAYER_ACTION_BET_FOLD,
    }
}